application: waterthem
version: 1
runtime: python27
api_version: 1
threadsafe: yes

handlers:
- url: /favicon\.ico
  static_files: favicon.ico
  upload: favicon\.ico

- url: /s
  static_dir: app

- url: /test/hello
  script: test.hello

- url: /test/form.*
  script: test.form

- url: /test/user.*
  script: test.user

- url: .*
  script: main.app

libraries:
- name: webapp2
  version: "2.5.2"
